# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('present', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350, verbose_name='Имя концепции')),
                ('tooltip', models.TextField(max_length=700, verbose_name='Подсказка')),
                ('link', models.URLField(max_length=400, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Концепция',
                'verbose_name_plural': 'Концепции',
            },
        ),
        migrations.CreateModel(
            name='MoreTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350, verbose_name='Имя инструмента')),
                ('tooltip', models.TextField(max_length=700, verbose_name='Подсказка')),
                ('link', models.URLField(max_length=400, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Дополнительный инструмент',
                'verbose_name_plural': 'Дополнительный инструменты',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350, verbose_name='Имя технологии')),
                ('icon', models.ImageField(upload_to='', verbose_name='Иконка')),
                ('tooltip', models.TextField(max_length=700, verbose_name='Подсказка')),
                ('link', models.URLField(max_length=400, verbose_name='Ссылка')),
                ('progress', models.IntegerField(verbose_name='Прогресс от 1 до 100%')),
            ],
            options={
                'verbose_name': 'Технология',
                'verbose_name_plural': 'Технологии',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='', verbose_name='Иконка')),
                ('name', models.CharField(max_length=350, verbose_name='Имя инструмента')),
                ('tooltip', models.TextField(max_length=700, verbose_name='Подсказка')),
                ('link', models.URLField(max_length=400, verbose_name='Ссылка')),
                ('progress', models.IntegerField(verbose_name='Прогресс от 1 до 100%')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'Работа', 'verbose_name_plural': 'Работы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='work',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата выполнения'),
        ),
    ]
