# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('present', '0002_auto_20170730_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='icon',
            field=models.ImageField(upload_to='icons/', verbose_name='Иконка'),
        ),
    ]
