# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('present', '0002_auto_20170405_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=250, verbose_name='Ссылка на работу')),
                ('desc', models.CharField(max_length=350, verbose_name='Описание работы')),
                ('img', models.ImageField(upload_to='/works/', verbose_name='Картинка изображения')),
            ],
        ),
    ]
