# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('present', '0003_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
