# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import present.models


class Migration(migrations.Migration):

    dependencies = [
        ('present', '0004_auto_20170730_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tool',
            options={'verbose_name': 'Инструмент', 'verbose_name_plural': 'Инструменты'},
        ),
        migrations.AddField(
            model_name='work',
            name='additionalTolls',
            field=models.ManyToManyField(to='present.MoreTool', verbose_name='Другие интсрументы'),
        ),
        migrations.AddField(
            model_name='work',
            name='full_desc',
            field=models.TextField(blank=True, max_length=4096, null=True, verbose_name='Описание проекта'),
        ),
        migrations.AddField(
            model_name='work',
            name='slide_1',
            field=models.ImageField(blank=True, null=True, upload_to=present.models.work_direcroty, verbose_name='Изображение работы 1'),
        ),
        migrations.AddField(
            model_name='work',
            name='slide_2',
            field=models.ImageField(blank=True, null=True, upload_to=present.models.work_direcroty, verbose_name='Изображение работы 2'),
        ),
        migrations.AddField(
            model_name='work',
            name='slide_3',
            field=models.ImageField(blank=True, null=True, upload_to=present.models.work_direcroty, verbose_name='Изображение работы 3'),
        ),
        migrations.AddField(
            model_name='work',
            name='slide_4',
            field=models.ImageField(blank=True, null=True, upload_to=present.models.work_direcroty, verbose_name='Изображение работы 4'),
        ),
        migrations.AddField(
            model_name='work',
            name='slide_5',
            field=models.ImageField(blank=True, null=True, upload_to=present.models.work_direcroty, verbose_name='Изображение работы 5'),
        ),
        migrations.AddField(
            model_name='work',
            name='slide_6',
            field=models.ImageField(blank=True, null=True, upload_to=present.models.work_direcroty, verbose_name='Изображение работы 6'),
        ),
        migrations.AddField(
            model_name='work',
            name='technologies',
            field=models.ManyToManyField(to='present.Technology', verbose_name='Технологии'),
        ),
        migrations.AddField(
            model_name='work',
            name='tolls',
            field=models.ManyToManyField(to='present.Tool', verbose_name='Инструменты'),
        ),
        migrations.AlterField(
            model_name='work',
            name='desc',
            field=models.CharField(max_length=350, verbose_name='Описание внутри тега alt'),
        ),
        migrations.AlterField(
            model_name='work',
            name='img',
            field=models.ImageField(upload_to=present.models.work_direcroty, verbose_name='Изображение работы'),
        ),
    ]
