# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('present', '0004_work_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='img',
            field=models.ImageField(upload_to='works/', verbose_name='Изображение работы'),
        ),
    ]
