# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('present', '0006_auto_20170801_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='is_showen',
            field=models.BooleanField(default=True, verbose_name='Отобразить?'),
        ),
    ]
