# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('present', '0007_work_is_showen'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='is_showen',
            field=models.BooleanField(default=True, verbose_name='Отобразить?'),
        ),
        migrations.AddField(
            model_name='moretool',
            name='is_showen',
            field=models.BooleanField(default=True, verbose_name='Отобразить?'),
        ),
        migrations.AddField(
            model_name='technology',
            name='is_showen',
            field=models.BooleanField(default=True, verbose_name='Отобразить?'),
        ),
        migrations.AddField(
            model_name='tool',
            name='is_showen',
            field=models.BooleanField(default=True, verbose_name='Отобразить?'),
        ),
    ]
