# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('present', '0008_auto_20170802_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concept',
            old_name='is_showen',
            new_name='is_showed',
        ),
        migrations.RenameField(
            model_name='moretool',
            old_name='is_showen',
            new_name='is_showed',
        ),
        migrations.RenameField(
            model_name='technology',
            old_name='is_showen',
            new_name='is_showed',
        ),
        migrations.RenameField(
            model_name='tool',
            old_name='is_showen',
            new_name='is_showed',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='is_showen',
            new_name='is_showed',
        ),
        migrations.AddField(
            model_name='work',
            name='name',
            field=models.CharField(blank=True, max_length=350, verbose_name='Имя работы'),
        ),
        migrations.AlterField(
            model_name='work',
            name='additionalTools',
            field=models.ManyToManyField(blank=True, to='present.MoreTool', verbose_name='Другие интсрументы'),
        ),
        migrations.AlterField(
            model_name='work',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='present.Technology', verbose_name='Технологии'),
        ),
        migrations.AlterField(
            model_name='work',
            name='tools',
            field=models.ManyToManyField(blank=True, to='present.Tool', verbose_name='Инструменты'),
        ),
    ]
