# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_images',
            field=models.ManyToManyField(blank=True, related_name='album_images', to='album.AlbumImage', verbose_name='Изображения альбома'),
        ),
    ]
