# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20180128_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album_images',
        ),
        migrations.AddField(
            model_name='albumimage',
            name='album',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='album.Album', verbose_name='Альбом'),
        ),
    ]
