# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 14:17
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Глобальная настройка', max_length=100, verbose_name='Имя настройки')),
                ('widgets', models.TextField(blank=True, max_length=8196, null=True, verbose_name='Метрики, виджеты и прочее')),
                ('meta', models.TextField(blank=True, max_length=300, null=True, verbose_name='Глобальное META-описание сайта')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='+7 (985) 905-12-51', max_length=90, null=True, verbose_name='Телефон в нижней части страници')),
                ('default_link_color', colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Стандартный цвет ссылок')),
                ('default_link_hover_color', colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Стандартный цвет ссылок при наведении')),
                ('default_color', colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Цвет шрифта по умолчанию')),
                ('default_bg', colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Цвет фона сайта')),
                ('preloader_color', colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Цвет прелоадера')),
                ('curtain_bg', colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Цвет фона предварительной загрузки')),
                ('thumb_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumb_photo', to='album.AlbumImage', verbose_name='Твоё лицо')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
                'db_table': 'site_settings',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Тэг')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=350, verbose_name='Имя работы')),
                ('task', models.TextField(max_length=350, verbose_name='Цель проекта')),
                ('task_en', models.TextField(blank=True, max_length=350, verbose_name='Цель проекта(en)')),
                ('url', models.URLField(max_length=250, verbose_name='Ссылка на работу')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('slug', models.SlugField(unique=True)),
                ('is_shown', models.BooleanField(default=True, verbose_name='Отобразить?')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_album', to='album.Album', verbose_name='Альбом')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
                'db_table': 'my_works',
            },
        ),
    ]
