# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=36, verbose_name='Имя')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=24, null=True, verbose_name='Номер телефона')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Глобальная настройка', max_length=100, verbose_name='Имя настройки')),
                ('widgets', models.TextField(blank=True, max_length=8196, null=True, verbose_name='Метрики, виджеты и прочее')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='+7 (985) 905-12-51', max_length=90, null=True, verbose_name='Телефон в нижней части страници')),
                ('skype', models.CharField(blank=True, default='fanyxxx1234', max_length=90, null=True, verbose_name='Skype')),
                ('thumb_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumb_photo', to='album.AlbumImage', verbose_name='Твоё лицо')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
                'db_table': 'site_settings',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Тэг')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=350, verbose_name='Имя работы')),
                ('task', models.TextField(max_length=350, verbose_name='Цель проекта')),
                ('task_en', models.TextField(blank=True, max_length=350, verbose_name='Цель проекта(en)')),
                ('url', models.URLField(max_length=250, verbose_name='Ссылка на работу')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('slug', models.SlugField(unique=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_album', to='album.Album', verbose_name='Альбом')),
                ('tags', models.ManyToManyField(blank=True, related_name='work_tags', to='app.Tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
                'db_table': 'my_works',
            },
        ),
    ]
