# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Название страницы во вкладке', max_length=100, verbose_name='Заголовок')),
                ('meta', models.TextField(blank=True, max_length=300, null=True, verbose_name='META-описание сайта')),
                ('content', models.TextField(blank=True, max_length=16000, null=True, verbose_name='Контент страницы')),
                ('scripts', models.TextField(blank=True, help_text='Можно вставить код, который будет работать только на текущей странице.', max_length=4085, null=True, verbose_name='Скрипты')),
                ('works', models.ManyToManyField(to='app.Work', verbose_name='Работы')),
            ],
            options={
                'verbose_name': 'Страница "Портфолио"',
                'verbose_name_plural': 'Страница "Портфолио"',
                'db_table': 'data_portfolio_page',
            },
        ),
    ]
