# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Название страницы во вкладке', max_length=100, verbose_name='Заголовок')),
                ('meta', models.TextField(blank=True, max_length=300, null=True, verbose_name='META-описание сайта')),
                ('main_title', models.CharField(blank=True, help_text='Заголовок(можно обернуть в ссылку)', max_length=500, null=True, verbose_name='Заголовок страницы')),
                ('content', models.TextField(blank=True, help_text='Заголовок - h3, параграф - p.', max_length=16000, null=True, verbose_name='Контент страницы')),
                ('scripts', models.TextField(blank=True, help_text='Можно вставить код метрик, который будет работать только на текущей странице.', max_length=4085, null=True, verbose_name='Скрипты')),
                ('phone_1', models.CharField(blank=True, default='+7 (343) 36-16-911', max_length=90, null=True, verbose_name='Телефон 2')),
                ('phone_2', models.CharField(blank=True, default='+7 (922) 18-16-911', max_length=90, null=True, verbose_name='Телефон 1')),
                ('map', models.TextField(blank=True, default='<iframe class=\'mapContainer__map\' src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2181.9975502050816!2d60.63935701597335!3d56.84598588085985!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x43c16c2be5298e21%3A0x77522d799d8f3f75!2z0YPQuy4g0J_QtdGA0LLQvtC80LDQudGB0LrQsNGPLCA3Nywg0JXQutCw0YLQtdGA0LjQvdCx0YPRgNCzLCDQodCy0LXRgNC00LvQvtCy0YHQutCw0Y8g0L7QsdC7LiwgNjIwMDYy!5e0!3m2!1sru!2sru!4v1508837567170" width="100%" height="600" frameborder="0" style="border:0" allowfullscreen></iframe>', help_text='Карта, которая отображается в контактах', max_length=2048, null=True, verbose_name='Окно с картой')),
            ],
            options={
                'verbose_name': 'Страница "Контакты"',
                'verbose_name_plural': 'Страница "Контакты"',
                'db_table': 'data_contacts_page',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Название страницы во вкладке', max_length=100, verbose_name='Заголовок')),
                ('meta', models.TextField(blank=True, max_length=300, null=True, verbose_name='META-описание сайта')),
                ('main_title', models.CharField(blank=True, help_text='Заголовок(можно обернуть в ссылку)', max_length=500, null=True, verbose_name='Заголовок страницы')),
                ('content', models.TextField(blank=True, help_text='Заголовок - h3, параграф - p.', max_length=16000, null=True, verbose_name='Контент страницы')),
                ('scripts', models.TextField(blank=True, help_text='Можно вставить код метрик, который будет работать только на текущей странице.', max_length=4085, null=True, verbose_name='Скрипты')),
            ],
            options={
                'verbose_name': 'Страница "Главная"',
                'verbose_name_plural': 'Страница "Главная"',
                'db_table': 'data_home_page',
            },
        ),
    ]
