# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('page_title', models.CharField(help_text='Название страницы во вкладке', max_length=100, verbose_name='Заголовок')),
                ('meta', models.TextField(blank=True, max_length=300, null=True, verbose_name='META-описание сайта')),
                ('content', models.TextField(blank=True, max_length=16000, null=True, verbose_name='Контент страницы')),
                ('scripts', models.TextField(blank=True, help_text='Можно вставить код, который будет работать только на текущей странице.', max_length=4085, null=True, verbose_name='Скрипты')),
            ],
            options={
                'verbose_name': 'Страница "Обо мне"',
                'verbose_name_plural': 'Страница "Обо мне"',
                'db_table': 'about_page',
            },
        ),
        migrations.CreateModel(
            name='ArticlesPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('page_title', models.CharField(help_text='Название страницы во вкладке', max_length=100, verbose_name='Заголовок')),
                ('meta', models.TextField(blank=True, max_length=300, null=True, verbose_name='META-описание сайта')),
                ('content', models.TextField(blank=True, max_length=16000, null=True, verbose_name='Контент страницы')),
                ('scripts', models.TextField(blank=True, help_text='Можно вставить код, который будет работать только на текущей странице.', max_length=4085, null=True, verbose_name='Скрипты')),
            ],
            options={
                'verbose_name': 'Страница "Статьи"',
                'verbose_name_plural': 'Страница "Статьи"',
                'db_table': 'articles_page',
            },
        ),
        migrations.CreateModel(
            name='PortfolioPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('page_title', models.CharField(help_text='Название страницы во вкладке', max_length=100, verbose_name='Заголовок')),
                ('meta', models.TextField(blank=True, max_length=300, null=True, verbose_name='META-описание сайта')),
                ('content', models.TextField(blank=True, max_length=16000, null=True, verbose_name='Контент страницы')),
                ('scripts', models.TextField(blank=True, help_text='Можно вставить код, который будет работать только на текущей странице.', max_length=4085, null=True, verbose_name='Скрипты')),
                ('works', models.ManyToManyField(blank=True, to='app.Work', verbose_name='Работы')),
            ],
            options={
                'verbose_name': 'Страница "Портфолио"',
                'verbose_name_plural': 'Страница "Портфолио"',
                'db_table': 'portfolio_page',
            },
        ),
        migrations.CreateModel(
            name='TechnologiesPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('page_title', models.CharField(help_text='Название страницы во вкладке', max_length=100, verbose_name='Заголовок')),
                ('meta', models.TextField(blank=True, max_length=300, null=True, verbose_name='META-описание сайта')),
                ('content', models.TextField(blank=True, max_length=16000, null=True, verbose_name='Контент страницы')),
                ('scripts', models.TextField(blank=True, help_text='Можно вставить код, который будет работать только на текущей странице.', max_length=4085, null=True, verbose_name='Скрипты')),
            ],
            options={
                'verbose_name': 'Страница "Обо мне"',
                'verbose_name_plural': 'Страница "Обо мне"',
                'db_table': 'technologies_page',
            },
        ),
    ]
