# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('page_title', models.CharField(help_text='Название страницы во вкладке', max_length=100, verbose_name='Заголовок')),
                ('meta', models.TextField(blank=True, max_length=300, null=True, verbose_name='META-описание сайта')),
                ('content', models.TextField(blank=True, max_length=16000, null=True, verbose_name='Контент страницы')),
                ('scripts', models.TextField(blank=True, help_text='Можно вставить код, который будет работать только на текущей странице.', max_length=4085, null=True, verbose_name='Скрипты')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'db_table': 'single_article_page',
            },
        ),
    ]
