# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-26 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_articlepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technologiespage',
            options={'verbose_name': 'Страница "Технологии"', 'verbose_name_plural': 'Страница "Технологии"'},
        ),
    ]
